parameters:
- name: command
  type: string

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: $(terraformVersion)
  displayName: Install terraform

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: $(azureSubscription)
    backendAzureRmResourceGroupName: 'ServerlessTest-RG'
    backendAzureRmStorageAccountName: 'tfstatedemo1'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: $(tfstateName)
    workingDirectory: $(workingDirectory)
  displayName: terraform init

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: ${{ parameters.command }}
    environmentServiceNameAzureRM: $(azureSubscription)
    workingDirectory: $(workingDirectory)
  displayName: terraform ${{ parameters.command }}