trigger:
- master

variables:
  terraformVersion: '1.3.6'
  azureSubscription: 'Azure Sponsorship'
  backendResourceGroup: 'ServerlessTest-RG'
  backendStorageAccount: 'tfstatedemo1'
  tfstateName: 'development.tfstate'
  workingDirectory: '$(Build.SourcesDirectory)/envs/dev'
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform_Plan
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: Development
    pool:
      vmImage: $(vmImage)
    steps:
    - template: templates/run-terraform.yml
      parameters:
        command: 'plan'

- stage: Terraform_Apply
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: Development
    pool:
      vmImage: $(vmImage)
    steps:
    - template: templates/run-terraform.yml
      parameters:
        command: 'apply'