name: 'Terraform Develop'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TERRAFORM_VERSION: 0.15.1
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./envs/dev

    steps:
    - uses: actions/checkout@v2

    - name: Use Terraform ${{ env.TERRAFORM_VERSION }}
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      run: |
        terraform init -backend-config="resource_group_name=ServerlessTest-RG" \
                       -backend-config="storage_account_name=tfstatedemo1" \
                       -backend-config="container_name=tfstate" -backend-config="key=develop.tfstate"

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
